name: ci

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
        with:
          version: "0.12.13"
      - run: make setup
      - run: make static-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
        with:
          version: "0.12.13"
      - run: make setup
      - run: make test
